# this will trigger the build only on main branch and on PRs
if: branch = main

language: minimal

services:
  - docker

env:
  global:
    - IMAGE_NAME=transformer-engine
    - IMAGE_TAG=0.0.2
    - BUILD_IMAGE=true

install:
  - sh scripts/travis/build.sh
